Creation Announcm. for recruting of Respo eProf L3
horizon-efrei/efreussite-webhooks pull request #11
Opened 2022-04-12 21:03 UTC by gtedavid

Creation of the announcement for the recrutement of a new Respo eProf L3

2022-04-14 21:34 UTC, gtedavid commented
Ready to be posted IF Form has been reviewed  (@melisandeGB )

2022-04-15 11:48 UTC, noftaly requested changes

2022-04-15 11:48 UTC, noftaly commented on resources/ANNOUNCEMENT_2024_RECHERCHE_RESPO_EPROF_L3_SEM_PAIRE2021_22.md
> +Pour toute personne intéressée, n'hésitez pas à remplir le **(formulaire)**[https://bit.ly/RespoL3_S6_2022] et/ou à envoyer un message :speech_balloon: privé à <@890084641317478400> pour en discuter
```suggestion
Pour toute personne intéressée, n'hésitez pas à remplir le **[formulaire]**(https://bit.ly/RespoL3_S6_2022) et/ou à envoyer un message :speech_balloon: privé à <@890084641317478400> pour en discuter plus en détail :slight_smile:
```

2022-04-15 11:48 UTC, noftaly commented on resources/ANNOUNCEMENT_2024_RECHERCHE_RESPO_EPROF_L3_SEM_PAIRE2021_22.md
> + - Du suivi des eProfs L3
```suggestion
 - Suivre les eProfs L3
```
"a la charge de du suivi" 😄

2022-04-15 11:48 UTC, noftaly commented on resources/ANNOUNCEMENT_2024_RECHERCHE_RESPO_EPROF_L3_SEM_PAIRE2021_22.md
> + - De la gestion du dossier dédié à son rôle sur le GDrive :GDrive:, et des enregistrements de son niveau sur le SharePoint :SharePoint:
```suggestion
 - La gestion du dossier dédié à son rôle sur le GDrive :GDrive:, et des enregistrements de son niveau sur le SharePoint :SharePoint: 
```
"a la charge de de la gestion" 😄

2022-04-16 05:53 UTC, gtedavid commented on resources/ANNOUNCEMENT_2024_RECHERCHE_RESPO_EPROF_L3_SEM_PAIRE2021_22.md
> + - De la gestion du dossier dédié à son rôle sur le GDrive :GDrive:, et des enregistrements de son niveau sur le SharePoint :SharePoint:
oups
j'aurais peut-être dû mettre
"gérer "
mais on va garder "la gestion de"
à part si tu préfère "gérer"

2022-04-16 08:42 UTC, melisandeGB approved these changes
ok :)

2022-04-16 08:44 UTC, gtedavid commented
@melisandeGB si tu as le temps, si tu ne l'as pas déjà fait peux-tu jeter un coup d'œil au GForm pls ?

2022-04-16 08:45 UTC, gtedavid commented
> ok :)

si tu as le temps, si tu ne l'as pas déjà fait peux-tu jeter un coup d'œil au GForm pls ?

2022-04-16 09:42 UTC, noftaly approved these changes

2022-04-16 09:54 UTC, merged