Création du brouillon d'annonce
horizon-efrei/efreussite-webhooks pull request #19
Opened 2022-06-10 08:46 UTC by gtedavid

@melisandeGB @noftaly sentez vous libre de commenter
est-ce que Marc a été ajouté au github ?

2022-06-10 08:49 UTC, gtedavid commented
j'aimerai que Marc puisse lire et modifier 
Mais jsp s'il a accepté l'invite pour rejoindre....

2022-06-10 09:04 UTC, melisandeGB requested changes

2022-06-10 09:04 UTC, melisandeGB commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +On vous invite à regarder les cannals de docs pour des annales, à partager des docs que vous aurez mais qui n'y sont pas et à poser vos questions
```suggestion
On vous invite à regarder les canaux de docs pour des annales, à partager des docs que vous aurez mais qui n'y sont pas et à poser vos questions. 
```

2022-06-10 09:04 UTC, melisandeGB commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +Faire un cours sur Ef'Réussite (Horizon)<:EfRussite:938151807228706886>, il est préférable d'intégrer l'association, si vous souhaitez y contribuer plus souvent, mais ça reste ouvert à toutes et à to
```suggestion
Faire un cours sur Ef'Réussite (Horizon)<:EfRussite:938151807228706886>, il est préférable d'intégrer l'association si vous souhaitez y contribuer plus souvent, mais ça reste ouvert à toutes et à tous !
```

2022-06-10 09:04 UTC, melisandeGB commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +Si vous souhaitez juste partager votre écran pour une explication ou expliquer à un petit groupe, vous avez juste besoin de mp <@370940255026675715> ou <@890084641317478400> pour qu'on vous donne le
```suggestion
Si vous souhaitez juste partager votre écran pour une explication ou expliquer à un petit groupe, vous avez juste besoin de mp <@370940255026675715> ou <@890084641317478400> pour qu'on vous donne le rôle `eProf Cours` et que vous puissiez partager votre écran dans le canal vocal de la matière.
```

2022-06-10 09:04 UTC, melisandeGB commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +Même, on pourrait planifier si vous êtes chaud un cours via le bot !
```suggestion
Même, on pourrait planifier, si vous êtes chauds, un cours via le bot !
```

2022-06-10 09:04 UTC, melisandeGB commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +On sait que ça a été difficile pour nous de trouver des eProfs pour vous donner des cours.
Est-ce que ce ne serait pas plutôt "Vous savez que ç'a été difficile pour nous" ?

2022-06-10 09:04 UTC, melisandeGB commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +On sait que ça a été difficile pour nous de trouver des eProfs pour vous donner des cours.
```suggestion
On sait que ç'a été difficile pour nous de trouver des eProfs pour vous donner des cours.
```

2022-06-10 10:27 UTC, gtedavid commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +On sait que ça a été difficile pour nous de trouver des eProfs pour vous donner des cours.
ç'a ?

2022-06-10 10:28 UTC, gtedavid commented
@noftaly j'ai fait une mauvaise manip pour le submit ?

2022-06-10 10:41 UTC, gtedavid commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +On sait que ça a été difficile pour nous de trouver des eProfs pour vous donner des cours.
Résolu dans la suggestion d'après et commit appliqué

2022-06-10 12:44 UTC, el-marc-bernard approved these changes
c'est parfait,. Tu peux le push ;)

2022-06-10 12:47 UTC, noftaly requested changes

2022-06-10 12:47 UTC, noftaly commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +On vous invite à regarder les canaux de docs pour des annales, à partager des docs que vous aurez mais qui n'y sont pas et à poser vos questions.
```suggestion
On vous invite à regarder les canaux de docs pour des annales, à y partager des docs que vous auriez mais qui n'y sont pas ; et à poser vos questions. 
```

2022-06-10 12:47 UTC, noftaly commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +https://bit.ly/EfRéussiteSP
```suggestion
[Voici le lien du SharePoint avec les enregistrements passés (Dossier L3)](https://horizonefrei.sharepoint.com/sites/recording/Enregistrements/Forms/AllItems.aspx?id=%2Fsites%2Frecording%2FEnregistrements%2FEnregistrements&p=true&ga=1)
```

Je sais pas si tu préfères, mais bon vu qu'on peut autant en profiter. Hésite pas a rejeter cette suggestion si tu préfères donner le lien

2022-06-10 12:47 UTC, noftaly commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +Faire un cours sur Ef'Réussite (Horizon)<:EfRussite:938151807228706886>, il est préférable d'intégrer l'association si vous souhaitez y contribuer plus souvent, mais ça reste ouvert à toutes et à tou
```suggestion
Pour faire un cours sur Ef'Réussite (Horizon)<:EfRussite:938151807228706886>, il est préférable d'intégrer l'association si vous souhaitez y contribuer plus souvent, mais ça reste ouvert à toutes et à tous !
```

chui pas convaincu par le "mais ca reste ouvert" car je comprends pas trop a quoi ca réfère le "ça" ? c'est "faire un cours" ? ou "intégrer l'assos" ? 😅

2022-06-10 12:47 UTC, noftaly commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +Même, on pourrait planifier, si vous êtes chauds, un cours via le bot !
```suggestion
Si ca vous plaît, on pourra même planifier un cours via le bot !
```

2022-06-10 12:47 UTC, noftaly commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +Bon courage pour mater ces Rattrapages 💪
```suggestion
Bon courage pour mater ces rattrapages 💪
```

2022-06-11 13:54 UTC, gtedavid commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +https://bit.ly/EfRéussiteSP
Alors, le souci, c'est que ça ne fonctionne pas (encore) avec le lien direct à cause de l'Efrei, ça serait beau en effet, mais on est obligé d'utiliser le lien bit ly

2022-06-11 13:54 UTC, gtedavid commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +https://bit.ly/EfRéussiteSP
Mais je garde le format

2022-06-11 13:58 UTC, gtedavid commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +Faire un cours sur Ef'Réussite (Horizon)<:EfRussite:938151807228706886>, il est préférable d'intégrer l'association si vous souhaitez y contribuer plus souvent, mais ça reste ouvert à toutes et à tou
en gros comme on a peu d'eProf pour les L3 surtout à jour dans les matières qui sont demandés, on reste ouvert à permettre celles et ceux qui veulent juste aider certains en difficulté ou réviser ensemble à distance à pouvoir le faire sans être eProf, et en laissant la porte ouverte s'ils/elles sont intéressés à en faire +

2022-06-11 15:06 UTC, gtedavid commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +Faire un cours sur Ef'Réussite (Horizon)<:EfRussite:938151807228706886>, il est préférable d'intégrer l'association si vous souhaitez y contribuer plus souvent, mais ça reste ouvert à toutes et à tou
est-ce que la proposition ci-dessus te va mieux ? @noftaly

2022-06-11 17:01 UTC, gtedavid commented on resources/ANNOUNCEMENT_2024_RAT_SPRING_2022.md
> +Faire un cours sur Ef'Réussite (Horizon)<:EfRussite:938151807228706886>, il est préférable d'intégrer l'association si vous souhaitez y contribuer plus souvent, mais ça reste ouvert à toutes et à tou
@melisandeGB tu en penses quoi ?

2022-06-12 18:40 UTC, merged