Annonce rentrée 2022 2023 FINAL
horizon-efrei/efreussite-webhooks pull request #28
Opened 2022-08-30 22:57 UTC by gtedavid

WILL BE POSTED ON 31st AUGUST 2022 AT 9AM UTC+00

2022-08-30 23:04 UTC, noftaly requested changes

2022-08-30 23:04 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +Les cours ont lieu sur Discord ou Teams et sont généralement enregistrés par les <@&821920726155395102>. Ils sont ensuite mis sur [SharePoint d'Horizon](https://bit.ly/EfRéussiteSP) * ¹
```suggestion
Les cours ont lieu sur Discord ou Teams et sont généralement enregistrés par les <@&821920726155395102>. Ils sont ensuite mis sur [SharePoint d'Horizon](https://bit.ly/EfRéussiteSP)¹
```

2022-08-30 23:04 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +*Liste des professeurs et de leur préférence de contact à venir (modifier prochainement)*
Ne pas oublier de remplir ca avant de merge

2022-08-30 23:04 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +<@&821921661661610004> sont les eProfs pour les cours en présentiel.
```suggestion
<@&821921661661610004> sont les eProfs pour les cours en présentiel.
```
ca va littéralement afficher
`@eProf Cours Présentiel sont les eProfs pour les cours en présentiel.`
c'est très redondant "X = X" c'est inutile de le préciser 😄

2022-08-30 23:04 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +🔹 **`On recrute !`**
```suggestion
🔹 **On recrute !**
```

2022-08-30 23:04 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +Comme l'année précédente, on recherche un responsable eProf L1, en L1 Classique/INT/R, ainsi qu'un co-responsable eProf L1, essentiellement en L2 pour pouvoir seconder et accompagner le respo eprof L
```suggestion
Comme l'année précédente, on recherche un <@&934144211815661658>, en L1 Classique/INT/R, ainsi qu'un co-responsable eProf L1, en L2 pour pouvoir accompagner le <@&934144211815661658> et l'aider à déterminer les matières qui auraient besoin de cours.
```

2022-08-30 23:04 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +:small_blue_diamond: **`Pour tout le monde`**
```suggestion
:small_blue_diamond: **Pour tout le monde**
```

btw je suis toujours pour supprimer cette section entièrement car elle n'apporte rien je trouve... ou au moins la réduire de 80%...

2022-08-30 23:04 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +:small_blue_diamond: **`Pour chaque promotion`**
Comme précisé sur l'autre PR merged, il faudrait tout mettre dans les salons spécifiques aux promos pour raccourcir l'annonce et ne montrer les messages qu'aux intéressés

2022-08-31 10:27 UTC, lauragossip commented on resources/global/2022-2023/Annonce de rentrée.md
> +:small_blue_diamond: **`Pour tout le monde`**
En soit elle permet à ceux qui ne connaisse pas le fonctionnement d'en savoir un peut plus et de rassurer les gens qui peuvent être perdu

2022-08-31 10:29 UTC, lauragossip commented on resources/global/2022-2023/Annonce de rentrée.md
> +:small_blue_diamond: **`Pour chaque promotion`**
Mais justement le but de tout rendre publique ça permet aux gens qui le veulent de lire ce qui peut les attendre et de savoir que la promo du dessus est la pour les aider car ils sont passé par la 
Après rien empêche aux personnes de lire que pour le promo et de lire la fin sans lire les autres promo

2022-08-31 13:19 UTC, gtedavid commented on resources/global/2022-2023/Annonce de rentrée.md
> +*Liste des professeurs et de leur préférence de contact à venir (modifier prochainement)*
j'ai pas les infos

2022-08-31 14:16 UTC, gtedavid commented on resources/global/2022-2023/Annonce de rentrée.md
> +<@&821921661661610004> sont les eProfs pour les cours en présentiel.
Donc on n'en parle pas ?

2022-08-31 14:29 UTC, iv-stpn requested changes, later dismissed
Organigramme en cours de modification

2022-08-31 14:29 UTC, iv-stpn commented on resources/global/2022-2023/Annonce de rentrée.md
> +Nous nous mettons aux couleurs de l'association, nous savons que certains aimaient l'ancien logo du serveur ; on le garde dans notre cœur et on dit bienvenue au nouveau logo !
```suggestion
Voici quelques infos à savoir pour bien commencer l'année 🎉 !

__🔸Concernant Ef'Réussite__ :
 - Pour toute question, n'hésitez pas à contacter <@1014452565208997889> (future nouvelle Responsable Ef'Réussite) et <@1014170847868616805> (futur nouveau Président d'Horizon), qui vous répondront dans les plus brefs délais 👋 
 
 - Nous ne sommes fermés à aucune idée ! Nous sommes ouverts à toutes et à tous, curieux et soucieux d'aider. 
 *Nos moyens d'aider sont toujours en évolution et l'innovation est au coeur de notre projet, donc exprimez-vous dans <#761924229208735825> et <#822840404968734790> 💬*
 
 -  **Les cours en présidentiel reprennent** en tandem avec le Mentorat 🌱
 *Les prochains cours en présentiel & co-modal seront **annoncés à leur reprise sur Ef'Réussite** :efreussite:*
 
 __🔸Concernant Horizon__ :
Qui dit rentrée... dit **__NOUVEAUTÉS__** 🚀
 
 - __**"Horizon : Web 🌐" devient "Horizon : OpenDEV 🌐"**__. Après le succès du projet [Okampus](myefrei.okampus.fr), qui sera utilisé par l'Efrei pour l'année 2022-23, OpenDEV accueille de nouveaux projets ! *Retrouvez toutes les infos sur [le Discord de OpenDEV 🌐](https://discord.gg/zDz6kwuP8S)*
 
 - Nos logos se mettent couleurs d'Horizon :horizon: ! Les fonds des logos [d'Ef'Réussite ⭐](https://discord.gg/7WKfyhghyn), du [Mentorat 🌱](https://discord.gg/G7fWxQZXqF) et de [OpenDEV 🌐](https://discord.gg/zDz6kwuP8S) passent au orange à la place du vert turquoise.
   *Nous savons que certains aimaient l'ancien logo du serveur ; nous le garderons dans notre cœur tout en disant bienvenue aux nouveaux logos !*
 
__🔸Concernant l'EFREI __ : 
- Le titre officiel des **Responsables Réussite Étudiante (RRE)** de l'EFREI (généralement appelés "Responsables de promo") devient **Responsable de Formation**
```

 - Pour ceux qui nous rejoignent si vous voyez pas certaines choses ou avez des questions, <#957735193068851240>, seulement visible par celles et ceux sans rôles, est fait pour vous ! 

Pas pertinent si les nouveaux arrivants ont le rôle "Choisis ton rôle" et ne voient que ce chan en plus des annonces
C'est très explicite et c'est assez loin dans l'annonce donc peu de chances que ce soit vu dans tous les cas
 
   Pour les rôles, vous pouvez regarder dans les canaux <#817741515564122143> (accès)  et  <#891362567476363274>/<#891362465718370405>.
   Les rôles dans <#892340236175147029> sont des rôles optionnels. Si vous êtes perdu, regardez ici <#892407797961089114> ou pingez <@&701774653940564078> ou <@&934147334760169574> si quelque chose n'est pas clair ;)
   
Pareil, suffisament explicite et loin dans l'annonce pour que ce ne soit pas pertinent de le préciser

@noftaly Il faudrait mettre en place le système de relance par MP au plus vite si les gens ne choisissent pas leurs rôles + les annonces de rentrée par MP, on en reparle après le 8 septembre

__🔸Concernant l'EFREI __ : 

@gtedavid  @lauragossip Aucune autre news pour l'Efrei, vous êtes sûrs ? Ce serait bien de mettre le max d'infos

Par exemple, on pourrait présenter le learning XP, ce serait pas mal :thinking:
Cela dit perso j'ai pas d'info à part que ça remplace la PAVE, et encore je suis même pas sûr que ça concerne tout le monde

2022-08-31 14:59 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +<@&821921661661610004> sont les eProfs pour les cours en présentiel.
Il n'y a pas besoin d'en parler 😄 et tout est déjà dans #guide-et-liens

2022-08-31 15:00 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +*Liste des professeurs et de leur préférence de contact à venir (modifier prochainement)*
Alors il faudrait enlever la ligne en italique 😅 
```suggestion
```

ou alors attendre d'avoir les informations avant de merge

2022-08-31 15:03 UTC, gtedavid commented on resources/global/2022-2023/Annonce de rentrée.md
> +*Liste des professeurs et de leur préférence de contact à venir (modifier prochainement)*
jsp quand je les aurais
j'ai envoyé le mail 3 jours après que je devais l'envoyer parce que je faisais des trucs à Cork

2022-08-31 15:44 UTC, lauragossip commented on resources/global/2022-2023/Annonce de rentrée.md
> +Nous nous mettons aux couleurs de l'association, nous savons que certains aimaient l'ancien logo du serveur ; on le garde dans notre cœur et on dit bienvenue au nouveau logo !
En vrai on a pas masse d'info mais on peut en parler en disant qu'on aura bientôt les infos concernant le learning XP

2022-09-01 16:41 UTC, gtedavid commented on resources/global/2022-2023/Annonce de rentrée.md
> +Nous nous mettons aux couleurs de l'association, nous savons que certains aimaient l'ancien logo du serveur ; on le garde dans notre cœur et on dit bienvenue au nouveau logo !
j'ai modifié ta proposition 
en accord avec des discussions avec @lauragossip

Extra
```
 __🔸Concernant l'EFREI __ : 
- Le titre officiel des **Responsables Réussite Étudiante (RRE)** de l'EFREI (généralement appelés "Responsables de promo") devient **Responsable de Formation**

```

2022-09-01 16:42 UTC, gtedavid commented on resources/global/2022-2023/Annonce de rentrée.md
> +<@&821921661661610004> sont les eProfs pour les cours en présentiel.
ça a été réglé

2022-09-01 16:44 UTC, gtedavid commented
> Organigramme en cours de modification

euh je crois que c'est fait je vais check

2022-09-01 16:48 UTC, gtedavid commented on resources/global/2022-2023/Annonce de rentrée.md
> +:small_blue_diamond: **`Pour chaque promotion`**
RAS
Corrigé avec Ivan
Now resolved

2022-09-01 16:48 UTC, gtedavid commented on resources/global/2022-2023/Annonce de rentrée.md
> +:small_blue_diamond: **`Pour tout le monde`**
il me semble que c'est corrigé

2022-09-01 16:49 UTC, gtedavid commented on resources/global/2022-2023/Annonce de rentrée.md
> +*Liste des professeurs et de leur préférence de contact à venir (modifier prochainement)*
C'est en cours
je modifie sur le fichier

2022-09-01 17:51 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +*M ZALAMAE - Mathématiques - federico.zalamea@efrei.fr*
```suggestion
*M. Zalamea - Mathématiques - [federico.zalamea@efrei.fr](mailto:federico.zalamea@efrei.fr)*
```
je ne sais pas si le mailto va fonctionner, à vérifier lors d'un draft déploy 😅

2022-09-01 17:53 UTC, gtedavid commented on resources/global/2022-2023/Annonce de rentrée.md
> +*M ZALAMAE - Mathématiques - federico.zalamea@efrei.fr*
ça le fait automatiquement non ?

2022-09-07 15:44 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +*Mme Marechal - Physiques - [catherine.marechal@efrei.fr](mailto:catherine.marechal@efrei.fr)* email avec description difficultés, elle enverra une réunion Teams
```suggestion
*M. Zalamea - Mathématiques - federico.zalamea@efrei.fr*
*M. Marshall Breton - Algorithmie - c.marshallbreton@gmail.com*
*Mme Daadaa - Mathématiques - mouna.daadaa@efrei.fr*
*Mme Marechal - Physiques - catherine.marechal@efrei.fr* (email avec description difficultés, elle enverra une réunion Teams)
```
le mailto marche pas :(

2022-09-07 16:10 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> + - Nos logos se mettent couleurs d'Horizon :horizon: ! Les fonds des logos [d'Ef'Réussite ⭐](https://discord.gg/7WKfyhghyn), du [Mentorat 🌱](https://discord.gg/G7fWxQZXqF) et de [OpenDEV 🌐](https://d
```suggestion
 - Nos logos se mettent couleurs d'Horizon <:horizon:1014536805510557908> ! Les fonds des logos [d'Ef'Réussite ⭐](https://discord.gg/7WKfyhghyn), du [Mentorat 🌱](https://discord.gg/G7fWxQZXqF) et de [OpenDEV 🌐](https://discord.gg/zDz6kwuP8S) passent au orange à la place du vert turquoise.
```

2022-09-07 16:10 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +** **
```suggestion
```
ca fait un saut de ligne en trop par rapport aux autres endroits

2022-09-07 16:11 UTC, noftaly commented on resources/global/2022-2023/Annonce de rentrée.md
> +🔹 **On recrute !**
```suggestion
🔹 **On recrute !**

```

2022-09-08 12:01 UTC, noftaly approved these changes

2022-09-08 12:02 UTC, merged