Update pour PEx
horizon-efrei/efreussite-webhooks pull request #40
Opened 2023-03-21 19:39 UTC by guifresp

Changement de pas mal de lignes flemme de détailler.

2023-03-21 19:46 UTC, gtedavid commented on resources/guide/Guide et liens.md
> +`Horizon` : **l'association d'entraide**, de peer-learning/peer-support et de projets collaboratifs de l'Efrei Paris Panthéon-Assas université <:pantheonassas:957749365940822107>, **qui gère <@&81713
`Horizon` : **l'association d'entraide** et de peer-learning/peer-support l'Efrei Paris Panthéon-Assas université <:pantheonassas:957749365940822107>, **qui gère <@&817131722399154177> <:efreussite_rond:1017359426249822280>** !

2023-03-21 19:49 UTC, gtedavid commented on resources/guide/Guide et liens.md
> +`Horizon` : **l'association d'entraide**, de peer-learning/peer-support et de projets collaboratifs de l'Efrei Paris Panthéon-Assas université <:pantheonassas:957749365940822107>, **qui gère <@&81713
`Horizon` : **l'association d'entraide** et de peer-learning/peer-support l'Efrei Paris Panthéon-Assas université <:pantheonassas:957749365940822107>, **qui gère <@&817131722399154177> <:efreussite_rond:1017359426249822280>** !

2023-03-21 19:52 UTC, guifresp commented on resources/guide/Guide et liens.md
> +`Horizon` : **l'association d'entraide**, de peer-learning/peer-support et de projets collaboratifs de l'Efrei Paris Panthéon-Assas université <:pantheonassas:957749365940822107>, **qui gère <@&81713
parfait!

2023-03-21 19:54 UTC, gtedavid requested changes

2023-03-21 19:54 UTC, gtedavid commented on resources/guide/Guide et liens.md
> +`Horizon` : **l'association d'entraide**, de peer-learning/peer-support et de projets collaboratifs de l'Efrei Paris Panthéon-Assas université <:pantheonassas:957749365940822107>, **qui gère <@&81713
> parfait!

il faut que tu le modifies dans le fichier @guifresp 😅

2023-03-21 19:58 UTC, guifresp commented on resources/guide/Guide et liens.md
> +`Horizon` : **l'association d'entraide**, de peer-learning/peer-support et de projets collaboratifs de l'Efrei Paris Panthéon-Assas université <:pantheonassas:957749365940822107>, **qui gère <@&81713
zut
okkk wait

2023-03-22 18:01 UTC, noftaly commented
Comme discuté hier avec David, ce n'est pas le bon repo : le repo des PEx est https://github.com/horizon-efrei/efreussite-pex-webhooks
Et David y a déjà soumis une PR pour mettre à jours les messages dans Guide et lien et dans Règles : https://github.com/horizon-efrei/efreussite-pex-webhooks/pull/1

2023-03-22 18:01 UTC, closed without merging