Ukraine events
horizon-efrei/efreussite-webhooks pull request #8
Opened 2022-03-05 09:25 UTC by gtedavid

comme dit précédemment
à prendre avec des pincettes,
c'est peut-être plus moi qui a besoin d'écrire un truc à ce propos parce que j ne peux pas rester non émotionnelle par rapport à ce qui s'y passe.....

2022-03-05 10:37 UTC, melisandeGB approved these changes

2022-03-05 10:37 UTC, melisandeGB commented on resources/ANNOUNCEMENT_ALL_UKRAINE_ONGOING_WAR.md
> +Comment ne pas rester indifférent à ce qui se passe en Ukraine....
```suggestion
Comment ne pas rester indifférent à ce qu'il se passe en Ukraine....
```

2022-03-05 10:37 UTC, melisandeGB commented on resources/ANNOUNCEMENT_ALL_UKRAINE_ONGOING_WAR.md
> +Si vous pouvez donner, donner, mais faites gaffe aux arnaques
```suggestion
Si vous pouvez donner, donnez, mais faites attention aux arnaques.
```

2022-03-05 10:52 UTC, noftaly requested changes

2022-03-05 10:52 UTC, noftaly commented on resources/ANNOUNCEMENT_ALL_UKRAINE_ONGOING_WAR.md
> +- Si vous trouvez une clé USB, un CD ou autre périphérique de stockage, ne les connectez JAMAIS à vos PC ou à d'autres PC. Si vous les avez trouvés au sein de l'EFREI, déposez-les à l'accueil et post
```suggestion
- Si vous trouvez une clé USB, un CD ou autre périphérique de stockage, ne les connectez JAMAIS à vos PC ou à d'autres PC. Si vous les avez trouvés au sein de l'EFREI, déposez-les à l'accueil et postez un message dans les groupes correspondants.
```

2022-03-05 10:52 UTC, noftaly commented on resources/ANNOUNCEMENT_ALL_UKRAINE_ONGOING_WAR.md
> +- Gardez une habitude d'utiliser l'email efrei.net exclusivement pour des activités liées à l'efrei et non personnelles.
```suggestion
- Gardez pour habitude d'utiliser l'email efrei.net exclusivement pour des activités liées à l'efrei et non personnelles.
```
Peut être que l'autre était correct mais je trouve que ca sonne mieux comme ca 😄

2022-04-12 12:00 UTC, closed without merging

2022-04-12 12:01 UTC, gtedavid commented
Archivage de l'annonce non publiée et qui sera abandonnée